### PR TITLE
Extend end-to-end tests in people chains

### PR DESCRIPTION
**Pull request by rockbmb**

### CODE REVIEW

**Comment by xlc** [comment]
can you push the yarn.lock file change

**Comment by rockbmb** [comment]
@xlc Hello!

It's already in the tree, and mine hasn't changed compared to `master`. Did you detect any issues?

Can I ask that you
1. modify [this line](https://github.com/open-web3-stack/polkadot-ecosystem-tests/pull/63/files#diff-a23064cf391a231f37ad9c5acf4b59982877d99f13af57620ba1d841610c2c58R393) in the subidentity test from `await peopleClient.api.rpc('dev_newBlock', { count: 2 })` to `await peopleClient.api.rpc('dev_newBlock', { count: 1 })`
2.  try running `yarn test people.e2e.test -t "setting on-chain identity, adding sub-identities"`
from the latest commit?

Subidentity extrinsics fail to be applied immediately after 1 block, but if you try the same thing in a local `polkadot.js` fork, it will work correctly - odd.

**Comment by xlc** [comment]
The CI is failing and you have modified package.json without modify yarn.lock.

**Comment by xlc** [comment]
also I don't really want any code in the root package. please have the polkadot tests in the polkadot packages under `./packages/polkadot/src`, and shared helper in `./packages/shared/src`

**Comment by rockbmb** [comment]
@xlc thank you for the review!

I will address your comments in coming commits.

**Comment by rockbmb** [comment]
@xlc I've addressed your review - could you take another look?

**Comment by xlc** [comment]
CI is still failing due to yarn.lock file

**Comment by xlc** [comment]
the lint error indicates multiple versions of chopsticks are included, which is not good. you can confirm it by looking the yarn.lock file
do a yarn update chopsticks should resolve the error. make sure you do yarn lint locally to confirm. otherwise delete yarn.lock file and regenerate it could also work. but that will update other packages as well, which isn't bad, but just may have unexpected side effects

**Comment by rockbmb** [comment]
`yarn lint` does confirm the issue.

In the end, I simply rebuilt `yarn.lock`. I inspected it, and there is now only one version of `@acala-network/chopsticks` being used.

**Comment by rockbmb** [comment]
I've found the issue with the latest CI failures. Pushing a fix.

**Review by xlc — APPROVED** [review]

**Pull request merged**
